name: datn
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ./Backend
    container_name: backend_service
    restart: always
    tty: true
    stdin_open: true
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run build && npm run start"
    env_file:
      - ./Backend/.env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "1000"
    ports:
      - "5000:5000"
    volumes:
      - ./Backend/src:/app/src
      - ./Backend/prisma:/app/prisma
      - ./Backend/.env:/app/.env
      - ./Backend/tsconfig.json:/app/tsconfig.json
      - ./Backend/tsconfig.seed.json:/app/tsconfig.seed.json
      - ./Backend/package.json:/app/package.json
      - ./Backend/nodemon.json:/app/nodemon.json
      - /app/node_modules
      - /app/dist
    depends_on:
      postgres:
        condition: service_healthy
  
  frontend:
    build: ./Frontend
    container_name: frontend_service
    restart: always
    env_file:
      - ./Frontend/.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "1000"
      WATCHPACK_POLLING: "true"
      WATCHPACK_AGGREGATION_TIMEOUT: "1000"
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend/src:/app/src
      - ./Frontend/public:/app/public
      - ./Frontend/index.html:/app/index.html
      - ./Frontend/.env:/app/.env
      - ./Frontend/vite.config.ts:/app/vite.config.ts
      - ./Frontend/tsconfig.json:/app/tsconfig.json
      - ./Frontend/tsconfig.app.json:/app/tsconfig.app.json
      - ./Frontend/eslint.config.js:/app/eslint.config.js
      - /app/node_modules
      - /app/dist
    depends_on:
      - backend
  mqtt-worker:
    build: ./Mqtt-worker
    container_name: mqtt_worker
    restart: always
    env_file:
      - ./Mqtt-worker/.env
    environment:
      NODE_ENV: "production"
    command: sh -c "npm run build && npm run start"
    depends_on:
      postgres:
        condition: service_healthy
      backend:
        condition: service_started
volumes:
  postgres_data:
    name: datn_postgres_data