name: datn

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./Backend
    container_name: backend_service
    restart: always
    env_file:
      - ./Backend/.env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm run build && npm run start"

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  mqtt-worker:
    build: ./Mqtt-worker
    container_name: mqtt_worker
    restart: always
    env_file:
      - ./Mqtt-worker/.env
    environment:
      NODE_ENV: "production"
    command: sh -c "npm run build && npm run start"
    depends_on:
      backend:
        condition: service_healthy
      postgres:
        condition: service_healthy

  frontend:
    build: ./Frontend
    container_name: frontend_service
    restart: always
    env_file:
      - ./Frontend/.env
    environment:
      VITE_API_URL: "http://localhost:5000"
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    command: npm run dev

volumes:
  postgres_data:
    name: datn_postgres_data